# Generated by Django 4.0 on 2021-12-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('color', models.CharField(choices=[('White', 'BLANCO'), ('Red', 'ROJO'), ('Blue', 'AZUL'), ('Black', 'NEGRO'), ('Green', 'VERDE'), ('Yellow', 'AMARILLO'), ('Brown', 'MARRON'), ('Silver', 'PLATEADO'), ('Golden', 'DORADO')], default='White', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
